package org.sorincos;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
/*import com.thoughtworks.selenium.Selenium;
import com.thoughtworks.selenium.*;
*/

public class Test1TestSeleniumIDE {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
	
	WebDriver driver = new FirefoxDriver();
	/*
    String baseUrl = "https://suitecrm.com/demo/";
    selenium = new WebDriverBackedSelenium(driver, baseUrl);
	*/
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: test1
    // Step # | name | target | value
    // 1 | open | /demo/ | 
	driver.get("https://suitecrm.com/demo/");
    // 2 | setWindowSize | 1366x720 | 
    driver.manage().window().setSize(new Dimension(1366, 720));
    // 3 | click | css=#menu-item-556011 .menu-text | 
    driver.findElement(By.cssSelector("#menu-item-556011 .menu-text")).click();
  }
}
